### ISSUE TITLE
Not Getting Notifications Automatically

### ISSUE THREAD

**Issue by mlavio829** [shusain93/OSXMessageProxy#16]
Hi,
I seem to be having an issue of not getting message notifications automatically.
I have configured the Applet on IFTTT. "If maker Event "imessageRecieved", then push a link"
If i manually click, check now on the IFTTT website, i get the notifications on my Android device and it works perfectly.
For some reason, however, it is not doing this automatically. Am i doing something wrong? or have i misconfigured something?

thanks
michael

**Comment by shusain93** [comment]
Can you screenshot your whole IFTTT applet? This is odd but doesn't seem to be an issue with message proxy

**Comment by mlavio829** [comment]
Really weird. I got it working automatically. Took a reboot and it started working.

**Comment by mlavio829** [comment]
Really weird. I got it working automatically. Took a reboot and it started working.
