### ISSUE TITLE
Would there be any reason this wouldn't work on a Hackintosh that has iMessage working?

### ISSUE THREAD

**Issue by crsmelee** [shusain93/OSXMessageProxy#18]
I want to build a Hackintosh for the sole reason of getting iMessage on Android. I just wanted to know if there would be any reason it isn't possible if the Hackintosh has iMessage up and running.

**Comment by shusain93** [comment]
It'll work fine. Do you have an issue or are you asking before?

**Comment by crsmelee** [comment]
I'm just asking before I venture off into this. I have another general question but I don't know if this is the right place to ask.

**Comment by shusain93** [comment]
Just ask instead of wasting time

**Comment by crsmelee** [comment]
Does the Andromeda app also work as an SMS messaging app or is it strictly iMessage?

**Comment by shusain93** [comment]
It works with SMS if you have an iPhone with SMS forwarding. So likely for
you no. Just keep both apps in a folder

**Comment by crsmelee** [comment]
If I were to work on the source code, how hard would it be to implement SMS support on the app and code that would detect if the other person was using imessage and if not switch to SMS?

**Comment by shusain93** [comment]
Not terribly but it'd require server and client support and lots of time.

**Comment by crsmelee** [comment]
Oh so I would also have to develop for the OSXMessageProxy side if I'd want that functionality?

**Comment by shusain93** [comment]
Yes since this isn't aiming to be a product. It's something I use because
my friends use iMessage. Maybe it'll come eventually but I've got school
and a job and other life so it's not important to me. If you add it make a
pull request and I'll love you forever
