### ISSUE TITLE
Server Outdated?

### ISSUE THREAD

**Issue by Auvenell** [shusain93/OSXMessageProxy#19]
![error](https://user-images.githubusercontent.com/13284784/31050431-d9e8274c-a617-11e7-8d59-8cce8a79106c.jpg)

Got this error. Not sure how to get started using this.

**Comment by Auvenell** [comment]
This was from the AndromedaB client

**Comment by Auvenell** [comment]
@shusain93 Really appreciate the great work you did with this. I would love to work on the scripts, but my understanding of object oriented C and Swift is limited

**Comment by shusain93** [comment]
You put a URL into the server address field. Just put the IP/domain name (192.168.0.3 in your case). Not all traffic of this app is over HTTP which is why is why I asked for just the host.

**Comment by Auvenell** [comment]
Thanks Salman, its working now!

**Comment by Auvenell** [comment]
@shusain93 Do you think it's possible to take the server data and hook it up to a web based JavaScript client?

**Comment by shusain93** [comment]
Yes, the server implementation is really simple (though undocumented :/) and is just JSON. I hate web dev though so you're on your own.

**Comment by Auvenell** [comment]
@shusain93 can I email you?

**Comment by shusain93** [comment]
About what? I much prefer all issues be fixed in public so that other people can in the future use them.

**Comment by Auvenell** [comment]
Just requesting permission to feature your work in a future tutorial video

**Comment by shusain93** [comment]
It's open source. Give full proper credit, acknowledge that it's unofficial (i.e. not endorsed by Apple).   I'd much prefer that you link to the release pages (https://github.com/shusain93/OSXMessageProxy/releases) instead of re-uploading the binaries but again I can't really stop you. Go ahead!
