### ISSUE TITLE
Server crashes

### ISSUE THREAD

**Issue by harveson** [shusain93/OSXMessageProxy#2]
Sometimes the server crashes unexpectedly.

**Comment by shusain93** [comment]
Yes thanks for the great bug report. Please include crash logs. Also, use the script to run it and not the application

**Comment by shusain93** [comment]
I've fixed two major crashes in the latest update. Download it and tell me if this solves the problems?

https://github.com/shusain93/OSXMessageProxy/releases/tag/1.1

**Comment by harveson** [comment]
The new version seems to solve the problem.
