### ISSUE TITLE
Can't retrieve messages running under High Sierra

### ISSUE THREAD

**Issue by mentalbob** [shusain93/OSXMessageProxy#21]
Upgraded to High Sierra and had several problems.   First of which AndromedaB generates the error Unable to Load ConversationJSONDatabase! (see pic).   Also,  It appears some errors show up in the OSXMessageProxy terminal window (see attachment).   The app does occasionally successfully open the database but the dates appear to be corrupted in the messages.   The push notification sent via IFTTT appears to be fine. 

![screenshot_20171018-114115](https://user-images.githubusercontent.com/16952694/31976087-47b71834-b903-11e7-8d0a-e202aca4c870.png)

[osxmessageproxyerror.txt](https://github.com/shusain93/OSXMessageProxy/files/1412978/osxmessageproxyerror.txt)

**Comment by shusain93** [comment]
So you can load it sometimes and it's fine except the dates? Very odd.  If you have ADB could you send me a logcat of the app when you get this error? It prints to the console. I don't have error reporting for this error.

 Also, what is the output of `http://<your_ip>:8735/conversations?t=<your_token>`? If possible could you select a full conversation/portion of the response and redact personal info and add it too? It's a gigantic JSON page so if you're familiar with it throw it into a viewer and see if you can find the issues.  I can't really tell if there's an issue pulling info from the DB (doesn't seem like it? except maybe the date format changed..)

Also, looking at your log it seems like fast messaging isn't working. Is that only for some people? Can you try a single recipient message and let me know if it works?

**Comment by mentalbob** [comment]
When I can get a connection,  the dates are definitely corrupt, causing sorting problems in the full list view as well as in an individual conversation.   Attached below is a snippet of the JSON response of the API you had me send.   Also, message sending is broken.  Watching the screen, it looks like it does switch the focus to Messages to attempt to do a slow send, but then nothing happens.  When I get a chance, I'll hook my phone up to ADB to get you the dump you want when I'm having DB load issues.

```
{ "service" : "iMessage", "IDs" : "+1407xxxxxxxx, 407yyyyyyy, 407zzzzzzz", "has_manual_display_name" : true, "lastMessage" : 
 { "is_sent" : 0, "human_name" : "Anne S", "error" : 0, "is_from_me" : 0, "date_read" : 410302720, "date" : 410302720000000000, "text" : "Happy new year!", "chat_id" : 32, "guid" : "DB0D07EC-FBA3-4548-8B2C-EA702E67C3DC", "has_attachments" : false, "sender" : "407xxxxxxx", "date_delivered" : 410302720, "message_id" : 4932 }
, "chat_id" : 32, "display_name" : "Anne S, Marilyn P, Terri S", "handle_id" : 27 }, 
{ "service" : "iMessage", "IDs" : "+1407xxxxxxx", "has_manual_display_name" : true, "lastMessage" : 
 { "is_sent" : 1, "human_name" : "Laurie G", "error" : 0, "is_from_me" : 1, "date_read" : 405977849, "date" : 405978108000000000, "text" : "407–XXX–XXXX", "chat_id" : 27, "guid" : "C49C73BF-5683-4A07-9270-268ACBD756B5", "has_attachments" : false, "sender" : "407xxxxxxx", "date_delivered" : 405977849, "message_id" : 3204 }
, "chat_id" : 27, "display_name" : "Laurie G", "handle_id" : 26 }, 
{ "service" : "SMS", "IDs" : "111xxxxxxx", "has_manual_display_name" : true, "lastMessage" : 
 { "is_sent" : 0, "error" : 0, "is_from_me" : 0, "date_read" : 440381824, "date" : 440381669000000000, "text" : "Per your request your PIN for wireless number xxxx has been changed. If this is an error call 800-331-0500 or 611.", "chat_id" : 111, "guid" : "0F30EAF6-A610-E49A-4C63-4A23496721F6", "has_attachments" : false, "sender" : "111xxxxxxx", "date_delivered" : 440381824, "message_id" : 11746 }
, "chat_id" : 111, "display_name" : "111xxxxxxx", "handle_id" : 103 }, 
{ "service" : "iMessage", "IDs" : "+1407xxxxxxx", "has_manual_display_name" : true, "lastMessage" : 
 { "is_sent" : 0, "human_name" : "Aaron S", "error" : 0, "is_from_me" : 0, "date_read" : 0, "date" : 452317848000000000, "text" : "I thanks", "chat_id" : 33, "guid" : "0FD5BFAA-A659-4841-92B3-8139C4A123FE", "has_attachments" : false, "sender" : "407xxxxxxx", "date_delivered" : 0, "message_id" : 17778 }
, "chat_id" : 33, "display_name" : "Aaron S", "handle_id" : 28 } 
]
```

**Comment by shusain93** [comment]
Well that's odd, they are 1 billion times larger than they should be LOL. Was the last one (from Aaron) received sometime around May 2nd, 2015? That's what I get when I divide by 1 billion and convert it to human time. 

There's a chance that Apple has patched something in High Sierra with UI automation. I'll look into it sometime when I get around to updating my server.

**Comment by mentalbob** [comment]
Yes, the correct date is 5/2/2015.

**Comment by shusain93** [comment]
Alright, I'll look into this over the weekend. This should be a simple `if high sierra, divide by 1 billion` sort of deal.

**Comment by mentalbob** [comment]
Thanks.  I still haven't had a chance to put AndromedaB under ADB. I won't
be able to get to it till next week.

**Comment by shusain93** [comment]
No need, I’ve already figured the issue out.

**Comment by mentalbob** [comment]
Nice!  Thanks!

**Comment by shusain93** [comment]
Alright, I've updated my server to High Sierra. Fixed the time stamp (was literally one if statement lol). 

If you click "Check for updates" on the server app you should be able to install the update. The update thing is a little janky so you can just download it manually. 

https://github.com/shusain93/OSXMessageProxy/releases/tag/1.2.2

Let me know if this fixes it for you!

**Comment by mentalbob** [comment]
Looks good!   It looks like outgoing messages are working again too.
