### ISSUE TITLE
El Capitan support

### ISSUE THREAD

**Issue by tristandesigns** [shusain93/OSXMessageProxy#22]
Is there any way I could get this running on El Capitan? It worked perfectly on Sierra but it was too slow and unstable.

**Comment by shusain93** [comment]
Did you try? Did you get a specific error? It should work since the DB is essentially the same.

**Comment by tristandesigns** [comment]
Yes, I have tried.
First of all, the application is only for macOS 10.12 and above, so it won't, even with the script
When I attempted to change the minimum macOS version in the Info.plist. I got it to run through the script.
However, here is what I get:
![screen shot 2017-10-25 at 5 34 03 pm](https://user-images.githubusercontent.com/10486660/32029648-d85ff5a2-b9aa-11e7-82fa-02ef4109a05d.png)

**Comment by shusain93** [comment]
most of that’s just part of the script trying to collect crash logs that aren’t there.

The major bit is the Killed: 9. That’s because the app includes symbols/code which only works for >10.12. I’ll try and compile for 10.11 tonight and let you know.

**Comment by tristandesigns** [comment]
Were you able to get this working on 10.11 by compiling it?

**Comment by tristandesigns** [comment]
I'm completely lost on how to try to compile this. How would I compile it for El Capitan?

**Comment by shusain93** [comment]
[MessageProxy.zip](https://github.com/shusain93/OSXMessageProxy/files/1420656/MessageProxy.zip)

Let me know if it works. This is a weird dev build since I'm in the middle of a big feature but I've just disabled it so it should be okay. Haven't tested it.

**Comment by tristandesigns** [comment]
Thank you so much! This worked perfectly. I really appreciated it.

**Comment by shusain93** [comment]
Can you replace the version I attached with a fresh copy downloaded from [here](https://github.com/shusain93/OSXMessageProxy/releases/1.2.2/)? If you don't you won't get auto-updates in the future and that's not great.
