### ISSUE TITLE
AddressBookErrorDomain Code=1002 "(null)"

### ISSUE THREAD

**Issue by vrchlabak** [shusain93/OSXMessageProxy#23]
Have been using the proxy and AndromedaB for the last several months. Except for the know issues (conversations not refreshing without restarting the Android app, inability to send pictures etc.), the proxy / app combo have been working amazingly well. Till this morning. Here is the message I am getting. can you please help?? Thanks!
![capture](https://user-images.githubusercontent.com/7145322/32116049-f5fca1c4-bafd-11e7-8133-9d674ae3716d.JPG)

**Comment by shusain93** [comment]
Are you having an actual issue? The Accounts/AddressBook API is really verbose and generate tons of weird errors and warnings. I need to fix the script because I've had a few people referencing them.

**Comment by vrchlabak** [comment]
Yes, I can't connect. Getting the "couldn't connect to endpoint" message.
Server didn't response. Com.android.volley.

 

Interestingly enough, the MessageProxy app on my Mac is saying it's ready (I
deleted the API protection key for the screenshot).

**Comment by vrchlabak** [comment]
Here is the full report:

**Comment by shusain93** [comment]
Have you restart the server/computer? The errors are benign. Also attachments don't work when you email them, you need to attach through the web. What if you, on the computer running the server, visit `http://<IP>:<PORT>/isUp?t=<your_token>`?

**Comment by vrchlabak** [comment]
I figured it out. My public IP address changed for some reason. I don't have
it reserved via and my ISP must have changed it overnight.

 

Is there any trick to prevent this from happening in the future???

 

Thanks for your help. Your response time to help with issues (even as stupid
as mine was) is amazing. And much appreciated.

**Comment by shusain93** [comment]
You can use a service like No-IP or DYNDNS but really that's something I can't help you with.

**Comment by vrchlabak** [comment]
Ok, thanks!

**Comment by ConProgramming** [comment]
I am having the same issue, but don't understand what he had to do to fix it. Can one  of you explain?

**Comment by shusain93** [comment]
Well it’s not a bug, this is just a really verbose Apple log message because I’m using address book for contacts. Any issue you have is unrelated.
