### ISSUE TITLE
Help with sending a message

### ISSUE THREAD

**Issue by KarinaFernandez** [shusain93/OSXMessageProxy#28]
Hi @shusain93 . First of all thank you so much for share this awesome API! 
I need some help sending a message. Is anywhere an example of use? 

Thanks in advance!

**Comment by shusain93** [comment]
Do you mean the API? If you're trying to get it working on Android there's already a client for that, Andromeda. 

The server interface is here https://github.com/shusain93/OSXMessageProxy/blob/master/MessageProxy/ViewController.swift#L136 . Let me know if you have any questions.
