### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by neilio** [shusain93/OSXMessageProxy#3]
Alright, here we go. I just pulled fresh copies of the server and Andromeda down, edited CONFIG.plist, and when I try to build I get the error "No such module 'GRDB'".

Did I miss installing a dependency?

**Comment by shusain93** [comment]
Are you using the .xcworkspace? It's a white icon vs the blue one. GRDB is the webserver installed using Cocoa pods and so to compile properly you need to use the special workspace . I thought of this after so if you're doing this already correctly read on

Hmm, this didn't happen last time I tried to clone but we'll work with. You need to use cocoa pods. Install it on your system and then cd into the project directory and run `pod install`

I swear I pushed the pods to the repo but guess what it doesn't work haha. I'll update the read me if you have to do this.

**Comment by neilio** [comment]
NEVERMIND I'm an idiot. I opened the wrong file 🙄. So you recommend I run this from the command line?

**Comment by shusain93** [comment]
Yeah, use the .command file in the main folder. Put the script in the same directory as the built application file and just double click the script. It happens lol

**Comment by neilio** [comment]
IT'S ALIVE. Thanks for all of your hard work!
