### ISSUE TITLE
Mojave Support

### ISSUE THREAD

**Issue by philow** [shusain93/OSXMessageProxy#31]
Any chance we can get support for Mojave 10.14.2

Just continually throws the error:

fatal error: attempted to read an unknown reference but the object was already deallocated

Thanks!

**Comment by shusain93** [comment]
Can you provide a full crash log? I'm running it right now on my Mojave server just fine. You'll need to enable Full Disk Access in Privacy settings but other than that it didn't require any changes

**Comment by philow** [comment]
I added it to Full Disk Access but still had the issue.  Thanks!  

Was working fine till I upgraded to Mojave of cource.  I should have stayed where I was I hardly use my Mac Mini anyway.  Mostly just to relay messages to my Android and Chrome OS devices :)

I attached the crash dump from MacOS.

[MessageProxyDump.txt](https://github.com/shusain93/OSXMessageProxy/files/2705671/MessageProxyDump.txt)

**Comment by shusain93** [comment]
If you use the StartIMProxy I believe you need to grant terminal (or whatever emulator) full disk access. I haven’t been use the script lately as I haven’t experienced any crashes but that’s just me.

**Comment by philow** [comment]
I added Terminal to Full Disk Access and that did it!  Thanks for the Support!
