### ISSUE TITLE
Implement sockets and sending to new conversations

### ISSUE THREAD

**Issue by harveson** [shusain93/OSXMessageProxy#4]
1. Need to send new messages (select from Contact). 
2. New messages not updating unless restart the app
3. Delivery status is slow.

**Comment by shusain93** [comment]
These should all be easily fixable as soon as I have time really.

2 and 3 can be achieved with a bit of a hack: if you rotate your device on any view it triggers a refresh. If you want to check if your message has been sent/delivered just rotate it. It'll be fixed eventually.

**Comment by shusain93** [comment]
I've mostly started work with the sockets bit. [Here's a quick demo](https://gfycat.com/FloweryUnsungJerboa)

**Comment by shusain93** [comment]
Check out v1.2. Sockets are added.
