### ISSUE TITLE
IFTTT Recipe

### ISSUE THREAD

**Issue by leonff8** [shusain93/OSXMessageProxy#7]
Hi there, I have followed your instructions and have managed to start a server on my mac, as well as port forwarded it. I am lost on the IFTTT making a recipe part. I started making the applet and am unsure of what you mean by Value 1, Value 2 and Value 3 and where that goes in the applet-making process. If you could clarify that would be great. Sorry for any inconvenience as I am an amateur with these things.

PS for andromeda app, do I need to create a domain name or is using my public IP address with port sufficient for the setup?

**Comment by shusain93** [comment]
These values are what you should see when you click the ingredients button when filling out the Pushbullet part. You'll need to plug them in as specified or how you feel. Where you put each value is essentially where you are putting each component of the notification.

**Comment by leonff8** [comment]
Ah so the Pushbullet service would be the action. Would I be pushing a note or a link?

**Comment by shusain93** [comment]
A link. The link (in the format in the instructions) will let you auto launch the app when you tap the notification

**Comment by leonff8** [comment]
![screen shot 2017-05-03 at 2 13 05 pm](https://cloud.githubusercontent.com/assets/28289802/25648020/ad86860e-300a-11e7-8f93-33729b7e6d34.png)

Sorry to bother you one last time, does this look anything like how it should be done?

**Comment by shusain93** [comment]
![img_1015](https://cloud.githubusercontent.com/assets/1606726/25648061/f0c794de-2f84-11e7-8910-c79a2c5c3797.PNG)

I mean it'll work, just won't give what you want. Fill it out like I did. Next time thought please try before asking?

**Comment by leonff8** [comment]
I apologize. I have been trying to send the messages but it has not been working. It appears a bigger problem lies somewhere else (probably with my server). I will keep trying to figure it out. Thank you so much for your time.

**Comment by shusain93** [comment]
Can you post your server log file? It should be in your home directory under iMessageProxy. The file should be today's date.

**Comment by leonff8** [comment]
[2017-05-03.txt](https://github.com/shusain93/OSXMessageProxy/files/972436/2017-05-03.txt)

**Comment by shusain93** [comment]
Does the app properly work/can you see and send messages? The log doesn't tell me much since you haven't really done anything. Have you received messages while the server is running?

**Comment by leonff8** [comment]
[2017-05-03.txt](https://github.com/shusain93/OSXMessageProxy/files/972442/2017-05-03.txt)
Here is an updated log file when I texted a message from myself to myself. It does not show "Got 1 new message" until i close the message proxy app and the script reopens it.

**Comment by leonff8** [comment]
Hi there, just wanted to say that everything is now working and thank you so much for your help. This is such an excellent project and I have learnt so much.
